apiVersion: apps/v1
kind: Deployment
metadata:
  name: static
  labels:
    app: static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - image: sgryczan/hci-nks-demo:static-5e905d5f845820f45e41ddf5c37cdedda794a8f1
        name: static-demo
        ports:
        - containerPort: 80

